name: Enable merged doctests
description: Temporarily enable unstable merged doctests on Rust 2021 edition
runs:
  using: composite
  steps:
    - name: Enable merged doctests
      shell: bash
      run: |
        echo "RUSTC_BOOTSTRAP=1" >> "$GITHUB_ENV"
        echo "RUSTDOCFLAGS=${RUSTDOCFLAGS:+$RUSTDOCFLAGS }-Zunstable-options --merge-doctests=yes" >> "$GITHUB_ENV"
